Repository JuanSeBestia/calculator-angular-tdd, pull requests merged in 2019-09, with the labels that each got.

#4 Update README.md
  README.md
Labels: documentation

#5 Add env file
  .env
Labels: enhancement

#7 Add lint function
  package.json
Labels: request feature

#9 Us 1 display
  karma.conf.js
  package.json
  src/app/components/display/display.component.html
  src/app/components/display/display.component.scss
  src/app/components/display/display.component.spec.ts
  src/app/components/display/display.component.ts
  src/app/tab2/tab2.module.ts
  src/app/tab2/tab2.page.html
  src/app/tab2/tab2.page.spec.ts
  src/app/tab2/tab2.page.ts
Labels: Functionality
